window.DEFAULT_SESSIONS = [
  {
    "id": 1,
    "title": "Control de derecha",
    "objective": "Mantener la pelota con altura y dirección antes de buscar velocidad.",
    "warmup": "Relevos por parejas: conducir una pelota con la pala, pasar por dos puertas y terminar con intercambio cooperativo.",
    "technique": "El entrenador alimenta desde media pista. Golpear de derecha a una zona amplia cruzada; recuperar la posición tras cada golpe. Series de 6 bolas, cambiando rol.",
    "live": "Dos jugadores cooperan cruzado. Tras 4 golpes, el jugador que recibe puede cambiar paralelo; el otro debe leer, desplazarse y reconstruir el intercambio.",
    "match": "Partido a 11 puntos. El punto solo se activa después de 3 golpes; vale doble si el error rival se provoca moviéndolo, no por potencia.",
    "mode": "fondo",
    "target": "cruzado"
  },
  {
    "id": 2,
    "title": "Control de revés",
    "objective": "Estabilizar el revés y recuperar una posición útil después del golpe.",
    "warmup": "Espejo con pala: uno se desplaza lateralmente y el compañero copia; al aviso, intercambio de revés en minipista.",
    "technique": "Alimentación al lado de revés. Preparación corta, contacto delante y salida hacia una diana cruzada. Alternar bola cómoda y bola con desplazamiento.",
    "live": "Peloteo diagonal de revés con una puerta central. Tras 4 bolas, se abre el punto y cada jugador puede atacar el espacio libre.",
    "match": "Tie-break. Punto doble cuando se gana usando el revés para crear espacio y el siguiente golpe para ocuparlo.",
    "mode": "fondo",
    "target": "cruzado"
  },
  {
    "id": 3,
    "title": "Dirección: cruzado y paralelo",
    "objective": "Elegir dirección según la posición del rival.",
    "warmup": "Juego de semáforo: verde = cruzado, azul = paralelo; el entrenador muestra color justo antes del bote.",
    "technique": "Desde fondo, alternar dos bolas cruzadas y una paralela. Prioridad: misma preparación y control de salida.",
    "live": "Intercambio libre. Se coloca una zona prohibida central: la pelota debe buscar amplitud. El cambio paralelo solo se permite con equilibrio.",
    "match": "Partido por zonas: 1 punto normal, 2 si se encuentra una esquina libre, 3 si la pareja explica qué desplazamiento rival provocó.",
    "mode": "fondo",
    "target": "paralelo"
  },
  {
    "id": 4,
    "title": "Saque",
    "objective": "Iniciar el punto con seguridad, profundidad e intención de avanzar.",
    "warmup": "Dianas de saque sin pala: lanzar por debajo hacia dos zonas y sumar puntos por precisión.",
    "technique": "Rutina completa: colocación, bote, impacto por debajo de cintura y primer paso hacia delante. Dos saques a cada lado con objetivo profundo.",
    "live": "Sacador y restador juegan los primeros 4 golpes. El sacador busca entrar; el restador intenta neutralizar con profundidad o globo.",
    "match": "Juegos empezando siempre en 30-30. Punto doble si la pareja sacadora llega equilibrada a red antes del cuarto golpe.",
    "mode": "saque",
    "target": "avance"
  },
  {
    "id": 5,
    "title": "Resto",
    "objective": "Neutralizar el saque y decidir entre profundidad, dirección o globo.",
    "warmup": "Recepción-reacción: atrapar pelotas lanzadas a derecha o revés y enviarlas a una puerta elegida.",
    "technique": "Restos desde posición real. Bloqueo corto, contacto delante y objetivo cruzado profundo; después, una serie de restos en globo.",
    "live": "Saque real y punto hasta el quinto golpe. El restador elige bola baja o globo según la subida del sacador.",
    "match": "Partido condicionado: el restador suma 2 si evita que la pareja sacadora volee cómoda en los dos primeros golpes.",
    "mode": "resto",
    "target": "defensa"
  },
  {
    "id": 6,
    "title": "Globo",
    "objective": "Ganar tiempo y recuperar espacio mediante altura y profundidad.",
    "warmup": "Batalla de alturas: superar una cinta imaginaria alta y hacer botar la pelota detrás de una línea.",
    "technique": "Desde fondo, alimentación cómoda. Abrir la cara de la pala y enviar el globo a una zona profunda; alternar derecha y revés.",
    "live": "Pareja en fondo contra pareja en red. Los defensores deben recuperar la red usando un globo; después el punto es libre.",
    "match": "Partido ataque-defensa. Dos puntos por recuperar la red con globo y mantenerla durante dos contactos.",
    "mode": "fondo",
    "target": "globo"
  },
  {
    "id": 7,
    "title": "Volea de derecha",
    "objective": "Bloquear delante del cuerpo y dirigir sin balanceo excesivo.",
    "warmup": "Minivoleas cooperativas cerca de la red: récord de contactos con gesto corto y pies activos.",
    "technique": "Alimentación desde fondo a la volea de derecha. Bloqueo cruzado a zona profunda; una bola fija y otra con ajuste lateral.",
    "live": "Uno en red y otro en fondo. El jugador de red mantiene dos voleas y en la tercera puede buscar espacio; luego se abre el punto.",
    "match": "Rey de la red. La pareja atacante conserva el puesto si gana sin rematar; se premia colocación y cobertura.",
    "mode": "red",
    "target": "volea"
  },
  {
    "id": 8,
    "title": "Volea de revés",
    "objective": "Controlar la volea de revés y cerrar el centro con la pareja.",
    "warmup": "Escudo de red: por parejas, bloquear lanzamientos suaves dirigidos al cuerpo o al lado de revés.",
    "technique": "Alimentación a volea de revés. Contacto delante, pala estable y objetivo al centro o cruzado profundo.",
    "live": "Dos contra dos. El entrenador inicia al revés de uno de los voleadores; el punto continúa y la pareja debe moverse como bloque.",
    "match": "Partido: punto doble si la pareja gana después de cerrar correctamente el centro con una volea de revés.",
    "mode": "red",
    "target": "volea"
  },
  {
    "id": 9,
    "title": "Chiquita",
    "objective": "Jugar bajo a los pies para poder avanzar sin regalar la volea.",
    "warmup": "Puertas bajas: pasar la pelota por debajo de una cuerda o referencia y hacerla botar cerca de la red.",
    "technique": "Desde fondo, golpe suave a los pies del voleador. Después del impacto, dar dos pasos de avance y recuperar si la bola queda alta.",
    "live": "Fondo contra red. El defensor combina chiquita y globo; solo puede subir si la respuesta rival queda por debajo de la red.",
    "match": "Partido: 2 puntos si la pareja conquista la red tras una chiquita; 1 si sube sin ventaja pero consigue sostener el punto.",
    "mode": "fondo",
    "target": "pies"
  },
  {
    "id": 10,
    "title": "Salida de pared de derecha",
    "objective": "Esperar el rebote y jugar con equilibrio desde defensa.",
    "warmup": "Lectura de rebotes: dejar pasar, señalar el punto de salida y atrapar la pelota tras pared.",
    "technique": "Alimentación a pared de fondo. Giro de hombros, distancia de seguridad y golpe después del rebote hacia zona cruzada.",
    "live": "Uno ataca desde red y otro defiende. Las primeras dos bolas deben tocar pared; después se juega libre buscando globo o bola baja.",
    "match": "Partido: el defensor suma doble si transforma una bola de pared en una recuperación de posición o contraataque.",
    "mode": "pared",
    "target": "cruzado"
  },
  {
    "id": 11,
    "title": "Salida de pared de revés",
    "objective": "Leer el rebote de revés sin invadir la trayectoria de la pelota.",
    "warmup": "Sombra con rebote: desplazarse, dejar pasar una pelota lanzada y colocarse detrás de su trayectoria.",
    "technique": "Bolas a pared de fondo sobre el revés. Preparación temprana, espera y dirección cruzada; alternar profundidad y globo.",
    "live": "Atacante en red contra defensor. Se inicia siempre a pared de revés; el defensor decide entre cruzado bajo o globo.",
    "match": "Tie-break ataque-defensa. El defensor obtiene 2 puntos si sale de la esquina sin dejar una volea cómoda.",
    "mode": "pared",
    "target": "defensa"
  },
  {
    "id": 12,
    "title": "Pared lateral y esquina",
    "objective": "Reconocer si la pelota abre o cierra y ajustar la trayectoria.",
    "warmup": "Predicción: el entrenador lanza a esquina y el alumno indica antes del rebote si la pelota abre o cierra.",
    "technique": "Series de bolas a lateral y doble pared. Prioridad a lectura y colocación; el golpe final es controlado a zona central.",
    "live": "Dos contra dos con inicio obligatorio en esquina. La defensa debe jugar tres golpes antes de poder contraatacar.",
    "match": "Partido: se bonifica continuar el punto tras doble pared; el error por precipitación resta el bonus acumulado.",
    "mode": "pared",
    "target": "esquina"
  },
  {
    "id": 13,
    "title": "Bandeja",
    "objective": "Conservar la red con profundidad y margen de seguridad.",
    "warmup": "Lanzamientos por encima del hombro a una zona profunda, coordinando giro y paso de ajuste.",
    "technique": "Globo del entrenador. Ajustes laterales, impacto alto-lateral y bandeja profunda cruzada; recuperar red tras golpear.",
    "live": "Pareja en red recibe globos alternos. Juega bandeja y defiende la siguiente bola viva manteniendo cobertura conjunta.",
    "match": "Partido: la pareja atacante puntúa doble si mantiene la red durante tres golpes después de una bandeja.",
    "mode": "aereo",
    "target": "bandeja"
  },
  {
    "id": 14,
    "title": "Víbora",
    "objective": "Acelerar con efecto lateral cuando la posición permite atacar.",
    "warmup": "Giros y lanzamientos laterales con pelota: buscar rotación de tronco sin perder equilibrio.",
    "technique": "Globo medio. Preparación compacta, contacto lateral y objetivo a verja o pared lateral; alternar con bandeja para comparar.",
    "live": "Bola viva desde globo. El jugador decide bandeja o víbora según altura y posición; el rival intenta contraatacar.",
    "match": "Partido: la víbora solo puntúa doble si fue una elección adecuada; si se fuerza desde mala posición, el punto vale doble al rival.",
    "mode": "aereo",
    "target": "vibora"
  },
  {
    "id": 15,
    "title": "Remate",
    "objective": "Identificar cuándo finalizar y cuándo mantener la red.",
    "warmup": "Saltos suaves y lanzamientos verticales: coordinación de armado, extensión y caída estable.",
    "technique": "Globos cómodos. Remate plano dirigido con seguridad; alternar con bandeja para entrenar la decisión, no solo la ejecución.",
    "live": "Dos contra dos: el entrenador lanza globos de distinta calidad. El atacante elige remate o golpe de continuidad y se juega el punto.",
    "match": "Partido: 2 puntos por remate ganador bien seleccionado; -1 bonus si se remata una bola sin posición y se pierde el control.",
    "mode": "aereo",
    "target": "remate"
  },
  {
    "id": 16,
    "title": "Bajada de pared",
    "objective": "Atacar una pelota alta tras pared sin perder control del punto.",
    "warmup": "Lectura alta-baja: reaccionar a globos y colocarse detrás del rebote antes de simular el golpe.",
    "technique": "Globo a pared de fondo. Esperar la caída, contactar delante y dirigir la bajada a pies o espacio central.",
    "live": "Pareja en fondo recibe globo y ejecuta bajada; la pareja de red bloquea y el punto continúa libre.",
    "match": "Partido: doble valor si la bajada crea una bola fácil para el compañero; no se premia solo el golpe ganador.",
    "mode": "pared",
    "target": "bajada"
  },
  {
    "id": 17,
    "title": "Defensa baja",
    "objective": "Resolver bolas a los pies y devolver tiempo a la pareja.",
    "warmup": "Pelotas rodadas y lanzadas a baja altura: ajustar pasos y elevar con control hacia una zona segura.",
    "technique": "Alimentación rápida a los pies. Preparación mínima, piernas flexionadas y salida baja cruzada o globo defensivo.",
    "live": "Pareja en red presiona a pareja en fondo. Los defensores deben sostener cuatro bolas y elegir cuándo lanzar el globo.",
    "match": "Partido: punto doble por recuperar una defensa difícil y volver a una formación equilibrada.",
    "mode": "fondo",
    "target": "defensa"
  },
  {
    "id": 18,
    "title": "Bloqueo de volea",
    "objective": "Absorber velocidad y devolver la pelota a una zona segura.",
    "warmup": "Reacción de manos: bloqueos cortos con pelotas suaves lanzadas desde poca distancia.",
    "technique": "Alimentación progresivamente rápida al cuerpo y a ambos lados. Pala delante, agarre estable y gesto mínimo.",
    "live": "Uno acelera desde fondo y otro bloquea en red. Tras tres bloqueos se abre el punto y ambos buscan espacio.",
    "match": "Partido: la pareja de red suma un bonus si neutraliza una bajada o golpe rápido sin perder posición.",
    "mode": "red",
    "target": "bloqueo"
  },
  {
    "id": 19,
    "title": "Saque y primera volea",
    "objective": "Conectar el saque con una llegada equilibrada a la red.",
    "warmup": "Carrera de secuencias: saque simulado, dos pasos, split-step y bloqueo de una pelota lanzada.",
    "technique": "Saque a objetivo y primera volea alimentada. Ajustar velocidad de subida para contactar en equilibrio.",
    "live": "Saque real, resto y primera volea; a partir del cuarto golpe, punto libre. Cambiar dirección de saque cada dos puntos.",
    "match": "Juegos completos. La pareja sacadora obtiene bonus si la primera volea se juega con control a zona prevista.",
    "mode": "saque",
    "target": "volea"
  },
  {
    "id": 20,
    "title": "Resto en globo",
    "objective": "Superar la presión inicial y disputar la red desde el resto.",
    "warmup": "Globo a dianas desde lanzamiento del compañero, variando distancia y lado de recepción.",
    "technique": "Saque controlado y resto en globo. Buscar altura sobre el jugador adelantado y profundidad sobre su espalda.",
    "live": "Saque real. Si el globo permite avanzar, la pareja restadora sube; si queda corto, debe reorganizar la defensa.",
    "match": "Partido a 4 juegos: bonus por recuperar la red desde el resto, siempre que ambos jugadores avancen coordinados.",
    "mode": "resto",
    "target": "globo"
  },
  {
    "id": 21,
    "title": "Volea de transición",
    "objective": "Resolver la primera pelota en movimiento antes de estabilizar la red.",
    "warmup": "Avance con split-step a señal visual y bloqueo suave hacia una puerta central.",
    "technique": "Desde media pista, alimentar una volea de transición. Jugar profunda, continuar el avance y recibir una segunda volea.",
    "live": "Dos contra dos: una pareja inicia en transición y debe decidir entre avanzar, frenar o retroceder según la respuesta.",
    "match": "Partido: doble punto si la pareja conquista la red sin dejar hueco central durante la transición.",
    "mode": "transicion",
    "target": "volea"
  },
  {
    "id": 22,
    "title": "Defensa de esquina",
    "objective": "Salir de la esquina usando lectura, altura y cooperación.",
    "warmup": "Mapa de rebotes: predecir y recorrer rutas de pelota en esquina sin pala; después, hacerlo con recepción.",
    "technique": "Alimentación a doble pared. Dejar espacio, orientar el cuerpo y devolver cruzado o globo según la salida.",
    "live": "Ataque contra defensa con inicio en esquina. El compañero debe cubrir el centro y ayudar a reconstruir el punto.",
    "match": "Partido: bonus si la pareja defiende dos bolas de esquina y termina recuperando una posición neutral.",
    "mode": "pared",
    "target": "esquina"
  },
  {
    "id": 23,
    "title": "Golpe aéreo para cerrar",
    "objective": "Elegir entre bandeja, víbora y remate según el globo recibido.",
    "warmup": "Tres señales: conservar, presionar o cerrar. El jugador representa el golpe adecuado con lanzamiento.",
    "technique": "Serie variable de globos. El entrenador asigna alturas y profundidades distintas; el jugador nombra y ejecuta su elección.",
    "live": "Dos contra dos con inicio de globo. La pareja atacante decide el golpe aéreo y debe justificar la elección al acabar el punto.",
    "match": "Super tie-break. Bonus solo cuando el golpe aéreo elegido coincide con la posición y calidad del globo.",
    "mode": "aereo",
    "target": "decision"
  },
  {
    "id": 24,
    "title": "Golpe elegido y evaluación",
    "objective": "Consolidar el golpe que cada grupo necesita y demostrarlo en juego real.",
    "warmup": "Reto de récord trimestral: regularidad, movilidad y comunicación por parejas.",
    "technique": "Cada pareja elige un golpe prioritario. El entrenador propone una tarea de 8 minutos con objetivo observable y corrección breve.",
    "live": "Juego de cuatro estaciones: fondo, pared, transición y red. En cada estación se inicia con el golpe elegido.",
    "match": "Festival final: partidos cortos con autoevaluación. Cada pareja fija un plan, lo prueba y lo modifica una vez.",
    "mode": "mixto",
    "target": "evaluacion"
  }
];
